blueprint:
  name: Auto Exhaust
  description: >
    Turn Exhaust Fan on and off based on Lights in Toilet.
    
  domain: automation
  source_url: https://gist.github.com/razaqad/a6378a44cb9d995d4ec2631e12800ca1
  input:
    lights:
      name: Light to monitor
      description: Lights that are linked with Exhaust Fan
      selector:
        entities:
          domain: lights
    exhaust_fan:
      name: Target Exhaust Fan
      description: Exhaust Fan
      selector:
        entities:
          domain: fans
    no_motion_wait:
      name: Wait time
      description: Time to wait until the light should be turned off.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    illuminance_sensor:
      name: Illuminance Sensor (Optional)
      description: "Sensor that decides if lights should be turned on based on the illuminance."
      default:
      selector:
        entit:
          domain: sensor
          device_class: illuminance
    illuminance_threshold:
      name: Illumincance Threshold (Optional)
      description: "Defines the illumincance threshold below which the lights should turn on."
      default: 300
      selector:
        number:
          min: 0
          max: 100000
          unit_of_measurement: lux
    binary_sensor_entity:
      name: Binary Sensor (Optional)
      description: "Binary Sensor that decides if lights should be turned on - state on is turn on lights."
      default:
      selector:
        entity:
          domain: binary_sensor
    guest_mode_entity:
      name: Guest Mode (Optional)
      description: "Binary Sensor that decides if lights shall Auto Turn Off. Guest Mode is on."
      default:
      selector:
        entity:
          domain: input_boolean
    target_light:
      name: Light
      description: "The lights to keep in sync."
      selector:
        target:
          entity:
            domain: light

mode: restart
max_exceeded: silent
