blueprint:
  name: Auto Exhaust
  description: >
    Turn Exhaust Fan on and off based on Lights in Toilet.
    
  domain: automation
  source_url: https://github.com/razaqad/HA/blob/main/auto_Exhaust.yaml
  input:
    exhaust_fan:
      name: Target Exhaust Fan
      description: Exhaust Fan
      selector:
        entity:
          domain: switch
    wait_time:
      name: Wait time
      description: Time to wait until the light should be turned off.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    guest_mode_entity:
      name: Guest Mode (Optional)
      description: "Binary Sensor that decides if lights shall Auto Turn Off. Guest Mode is on."
      default:
      selector:
        entity:
          domain: input_boolean
    target_light:
      name: Light
      description: "The lights to keep in sync."
      selector:
        target:
          entity:
            domain: light
            # multiple: true

# mode: restart
# max_exceeded: silent
